kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-volume
  namespace: default  
spec:  
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

